### PR TITLE
gql Queries for  getAllParking, getParkingById ,getAllInventory

### PR DESCRIPTION
**Pull request by bhumisha**

### CODE REVIEW

**Comment by bhumisha** [comment]
"GetAllParking Query -> it will return all parking searched by city and date. No login required"
Screen Shot 2021-05-16 at 12 26 08 AM

**Comment by bhumisha** [comment]
Screen Shot 2021-05-16 at 1 51 01 AM

**Review by akramsabbah9 — COMMENTED** [review]
We will need another query to get a user's reservations. I think this can be done by adding a [reservations] array to the User model, or adding a `getParkingByProviderId` query to the TypeDefs/resolvers.

**Comment by bhumisha** [comment]
> We will need another query to get a user's reservations. I think this can be done by adding a [reservations] array to the User model, or adding a `getParkingByProviderId` query to the TypeDefs/resolvers.

Yes we will add after Reservation Mutation.. thanks for suggestion.

**Review by akramsabbah9 — APPROVED** [review]

**Review by yulduzetta — APPROVED** [review]
lgtm!

**Pull request merged**
